### ISSUE TITLE
rownames error when running example

### ISSUE THREAD

**Issue by kramersu** [sdechaumet/ramopls#2]
Hello,

thanks for your tool. I used to be able to run it without issue, but lately I am getting a rownames error, even when running the example files:

 result <- run_AMOPLS(datamatrix = data_Ruiz2017$datamatrix,
+                      samplemetadata = data_Ruiz2017$samplemetadata, 
+                      factor_names = c("Exposure time", "Dose"))
Error: rownames incorrect length; expected 18 names, got 1  

I'm running: R version 4.3.1 (2023-06-16) -- "Beagle Scouts"

many thanks!

**Comment by sdechaumet** [comment]
Hello !

I'm happy to see someone using this package !
It was developped and tested on R 3.6.0 which is kind of old now.. So I'm not suprised about some problem when using a newer R version (and probably different packages).

I'll try too look at this next week and update R and all the dependencies.

**Comment by kramersu** [comment]
Hi there,
yeah, I guess being a package dev is a thankless task like that ;) You only hear from your your users when we have issues. But yes, we are using it and until recently it worked great! Thanks a lot for developing and looking forward to an updated version.
Best,
Susanne

**Comment by sdechaumet** [comment]
It was enjoyable to delve back into the code (which brought back a lot of memories ^^).
I've resolved the dependency issues and updated all the packages and R.
Please feel free to try again and provide feedback so I can close the issue. If you encounter difficulties setting up the dependencies, you can utilize renv with the renv.lock file to build them.

All the best.

**Comment by kramersu** [comment]
Heya, I reinstalled the package using remote but am still getting the same error. It still lists the build as rAMOPLS_1.0 though, so maybe that's still the old version?

Thanks!

**Comment by kramersu** [comment]
update: I installed manually from source and now it works! Thanks a lot!

**Comment by sdechaumet** [comment]
Hi ! I'm happy to here that, I'm closing the issue then 👍
